# Generated by Django 4.0.3 on 2022-04-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierAPI',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MedicalId', models.PositiveIntegerField()),
                ('Class', models.CharField(max_length=100)),
                ('ImagePath', models.ImageField(upload_to='')),
                ('UserId', models.CharField(max_length=500)),
                ('UsedDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAPI',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MedicalId', models.PositiveIntegerField()),
                ('PatientName', models.CharField(max_length=100)),
                ('PatientGender', models.CharField(max_length=6)),
                ('PatientAge', models.PositiveIntegerField()),
                ('PatientDOB', models.DateField()),
                ('PatientHeight', models.PositiveIntegerField()),
                ('PatientWeight', models.PositiveIntegerField()),
                ('UserId', models.CharField(max_length=500)),
                ('DateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
