# Generated by Django 4.0.3 on 2022-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifierapi',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='classifierapi',
            name='type',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
