# Generated by Django 4.0.3 on 2022-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifer', '0002_classifierapi_remarks_classifierapi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifierapi',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classifierapi',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
