# Generated by Django 3.2.5 on 2022-03-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='pname',
        ),
    ]
